title: Lyricall
owner: "Jan Černý"
ownersite: "https://blackblog.cz/"
description: "A minimalistic platform for poetry"
keywords: "poetry, lyrics, lyricall, free speach, open source, foss, decentralize, journalism, publish, book, education"
baseurl: ""                 # the subpath of your site, e.g. /blog
url: "https://lyricall.cz"  # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown

collections:
  posts:
    output: true
    custom_permalink_placeholders: ["author"]
    permalink: /:author/:title/
  articles:
    output: true
    custom_permalink_placeholders: ["author", "type"]
    permalink: /:author/:type/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      listed: true
      discussion: null
      note: null

excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jektex

paginate: 15
paginate_path: "/:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md
  - _site
  - scripts
  - _meta
  - makefile

