title: Lyricall
owner: "Jan Černý"
ownersite: "https://blackblog.cz/"
email:
description: "A minimalistic platform for poetry"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lyricall.cz" # the base hostname & protocol for your site, e.g. http://example.com
language: en
# Build settings
#
markdown: kramdown
theme: minima

kramdown:
    math_engine: katex

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md

excerpt_separator: <!--more-->

exclude: ["_site","scripts", "_meta"]
