title: Lyricall
owner: "Jan Černý"
ownersite: "https://blackblog.cz/"
description: "A minimalistic platform for poetry"
baseurl: ""                 # the subpath of your site, e.g. /blog
url: "https://lyricall.cz"  # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown
theme: minima

kramdown:
    math_engine: katex

collections:
  posts:
    output: true
    custom_permalink_placeholders: ["author"]
    permalink: /:author/:title/
  articles:
    output: true
    custom_permalink_placeholders: ["author", "type"]
    permalink: /:author/:type/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      listed: true
      discussion: null
      comments: false
      note: null

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-tidy

paginate: 30
paginate_path: "/:num/"

jekyll_tidy:
  exclude: ["_includes/*"]
  ignore_env: "development"
  compress_html: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md
  - _site
  - scripts
  - _meta
  - makefile

