title: Lyricall
owner: "Jan Černý"
ownersite: "https://blackblog.cz/"
email:
description: "A minimalistic platform for poetry"
baseurl: ""                 # the subpath of your site, e.g. /blog
url: "https://lyricall.cz"  # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown
theme: minima

kramdown:
    math_engine: katex

collections:
  posts:
    output: true
    custom_permalink_placeholders: ["author"]
    permalink: /:author/:title/

paginate: 50
paginate_path: "/#:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md
  - _site
  - scripts
  - _meta

excerpt_separator: <!--more-->
